### ISSUE TITLE
Mass patrolling doesn't work correctly

### ISSUE THREAD

**Issue by kizule** [Krinkle/mw-gadget-rtrc#115]
When I filter out specific user, and I want to use the "mass patrol" feature, edits get marked as patrolled in RTRC's interface, actions are visible in Special:Log, but edits aren't actually patrolled in Serbian Wikipedia.

When I manually patrol "change by change", it gets marked as patrolled correctly. There is a "Mark as patrolled" button missing in a diff, so I have to click on "[Mark]" each time.

**Comment by Krinkle** [comment]
@kizule I believe this is due to [T357693](https://phabricator.wikimedia.org/T357693), which is a regression in MediaWiki, where a change intended for MobileFrontend, has instead caused the `[mark as patrolled]` button to dissappear for all users, even for desktop, and for gadgets that fetch `action=render&diff=…&diffonly=1`.

**Comment by kizule** [comment]
Thank you so much for letting me know! One of sysops on Serbian Wikipedia has reported the exact issue from a task (not specifically for RTRC).

**Comment by kizule** [comment]
Everything is fine now, I'm closing this issue.
