### ISSUE TITLE
Make new page content scrollable (mw-rtrc-diff-newpage)

### ISSUE THREAD

**Issue by he7d3r** [Krinkle/mw-gadget-rtrc#21]
A user [suggested](https://pt.wikipedia.org/w/index.php?diff=37196766&oldid=37196312) in my talkpage that RTRC should provide a scollbar for the content of new pages (e.g. on [this configuration](https://pt.wikipedia.org/wiki/Usu%C3%A1rio%28a%29:Krinkle/RTRC?opt=%7B%22rc%22%3A%7B%22typeNew%22%3Atrue%7D%2C%22app%22%3A%7B%22autoDiff%22%3Atrue%7D%7D&kickstart=1) )

**Comment by Krinkle** [comment]
Since 6e9bf868f42f97638afcb2ac4365ad060a07a742 the height is now restricted to 400px for new pages. However it is not yet scrollable. Making it scrollable as-is would cause the tools to become invisible. We'll need to wrap the content in a separate element and apply the height restriction and scrollbar to that.

**Comment by Krinkle** [comment]
Declining for now, but feel free to create a new task at <https://phabricator.wikimedia.org/tag/gadget-whatleaveshere/>.
