### ISSUE TITLE
 Add the log to edit scroll list

### ISSUE THREAD

**Issue by Pegrolo** [Krinkle/mw-gadget-rtrc#36]
It would be very useful along with the edit tool also showed the log except for the verification of edit.

**Comment by Krinkle** [comment]
@Pegrolo I'm not sure I understand your question.

Are you asking for the "My patrol link" link to go to a page that does not include autopatrol/rollback events? That is currently not possible due to [T27799](https://phabricator.wikimedia.org/T27799).

Or maybe you're asking for RTRC to support the ability to "mark as patrolled" log events (in addition to edits and new pages). That requires MediaWiki to build a patrol feature for log events, that is not currently possible. I would expect most users to prefer otherwise since most actions are restricted to administrators, whom presumably don't require verification for their actions.

The log actions can still be viewed outside RTRC however, they are public at Special:Log (e.g. <https://en.wikipedia.org/wiki/Special:Log>)
