### ISSUE TITLE
use EventStreams?

### ISSUE THREAD

**Issue by shizhao** [Krinkle/mw-gadget-rtrc#70]
see https://wikitech.wikimedia.org/wiki/EventStreams

**Comment by Krinkle** [comment]
Closing for now as the current method is working fine. EventStreams would require subscribning to all wikis instead of just one, and it would not have any way to filter by user, page, patrol status, and to fetch the last hour when first opening the page. There is thus no obvious benefit to switching right now.

However, as part of https://github.com/Krinkle/mw-gadget-rtrc/issues/76 we will likely need to migrate to EventStreams in order to support monitoring multiple wikis at once. Let's revisit it as part of that.
