### ISSUE TITLE
Allow hiding patrolled edits by default

### ISSUE THREAD

**Issue by Botomatik** [Krinkle/mw-gadget-rtrc#77]
Hi, Is there any way to allow hiding patrolled edits by default, or would it be possible to add it? Would be very user-friendly for many I guess.

**Comment by Krinkle** [comment]
Yes, that is possible. It exists in RTRC since the first version, and works the same way as on Special:RecentChanges.

| English| French
|--|--
| <img width="846" alt="screen_shot_2018-05-12_at_02_05_39" src="https://user-images.githubusercontent.com/156867/39951339-3a0b0934-5589-11e8-8f3b-6211a636cabc.png">| <img width="647" alt="screen_shot_2018-05-12_at_02_03_50" src="https://user-images.githubusercontent.com/156867/39951320-07fa1d86-5589-11e8-9495-d741573ae963.png">


Note: This is the same as [Special:RecentChanges](https://fr.wiktionary.org/wiki/Special:RecentChanges). Do you see it there?

For both, only available when logged-in with patrol authentication permission (user group: "administrator", "reviewer", or "patroller").

**Comment by Botomatik** [comment]
I mean, right now we have to enable this option manually, every single time. It would be nice to have the possibility to have this option enabled automatically.

**Comment by Krinkle** [comment]
@Botomatik I understand. There is a permalink ability for remembering settings.

![capture](https://user-images.githubusercontent.com/156867/44432549-67cf8500-a59a-11e8-8d5c-2e5557f6d02e.png)

Does that work for you?

**Comment by Botomatik** [comment]
> 
> 
> @Botomatik I understand. There is a permalink ability for remembering settings.
> 
> ![capture](https://user-images.githubusercontent.com/156867/44432549-67cf8500-a59a-11e8-8d5c-2e5557f6d02e.png)
> 
> Does that work for you?

Thanks! Yes, it works. However it would be more convenient to use eg. localStorage to save and apply automatically previous settings to the tool, rather than using a bookmark (so as to be able to keep access RTRC from the sidebar).
