### ISSUE TITLE
version 1.3.5 broke RTL 

### ISSUE THREAD

**Issue by mat-mo** [Krinkle/mw-gadget-rtrc#78]
In version 1.3.4 the upper bar of [skip, next, mark, open in wiki, close] was on the right in RTL wikis, it moved to the left in this version, this is incorrect behavior.

**Comment by Krinkle** [comment]
@mat-mo Thanks for letting me know!

Can you show a screenshot of the issue? This is what it looks like for me:

|uselang=en|uselang=he
|--|--
|<img width="1418" alt="screen shot 2018-08-21 at 22 40 50" src="https://user-images.githubusercontent.com/156867/44430691-5c2c9000-a593-11e8-8464-b225e4de8f16.png">|<img width="1434" alt="screen shot 2018-08-21 at 22 40 55" src="https://user-images.githubusercontent.com/156867/44430692-5c2c9000-a593-11e8-8fde-6cba094c8fbc.png">

I enabled the use of CSSJanus in the Beta version 2 years ago (August 2016). With the release of v1.3.5, I added it to the regular version as well. It passes the user language to load.php, allowing CSSJanus to flip it, similar to what MediaWiki does.

Please let me know which specific parts of the interface you would prefer are not flipped, then I will disable CSSJanus for those styles.

Thanks!

**Comment by mat-mo** [comment]
skip next open in wiki and next should be right aligned. In addition the red warning triangle should be left aligned.

**Comment by Krinkle** [comment]
@mat-mo I'll fix the warning icon, thanks for spotting that.

About the diff tool links, I do not understand. Are you suggesting they should be attached to the diff title? Please look at the English version for comparison.

**Comment by mat-mo** [comment]
The diff was indeed attached to the title in previous versions. In the diff version above with EN userlang the title is on the left, and it should be on the right.

**Comment by Krinkle** [comment]
@mat-mo In RTRC, the diff tools have alway been on the side that is opposite of the title.

In English, users read the title on the left, with action choices on the right. This is similar to in MediaWIki where `[mark as patrolled]` and `[rollback]` are on the right-hand side diff (the part of the diff that matches currently viewing revision), and in MediaWiki "View history, Protect, Delete" actions are also on the right-hand side of the toolbar.

In RTL, thee are flipped by the default flipping behaviour. No customisations. In MediaWiki RTL, the title is on the right, and page actions and diff actions on the left.
 
In previous versions of RTRC, this was incorrect because I forgot to enable CSS flipping in RTRC. This is now fixed. I am sorry that it took so long, and it seems you got familiar and used to some of these bugs as being normal.

However, I do not have the time to develop different layouts in RTL and LTR for RTRC. Either the title is left and new revisions + tools right, or title is right and current revision + tools left. I can make it the same as English if you prefer, but they will not be together.

**Comment by mat-mo** [comment]
This makes a log of sense. I indeed got use to it. 
previous bugos behavior does however make some sense too, as the normal flow I had was to click on a diff (which is correctly on the right) then move my mouse just a bit above and pick one of the actions in the diff tool, now i need to drag the mouse all the way to the far left for every diff action.

**Comment by Krinkle** [comment]
Thanks, I'll close this report for now then.
